name: config-snap-demo 
base: core18
version: '0.1'
summary: Set the device config
description: |
  Initialize the device config

grade: stable
confinement: strict

apps:
  init:
    command: bin/run
    daemon: oneshot
    plugs:
      - network-setup-control


parts:
  netplan:
    plugin: dump
    source: netplan
    organize:
      "*": /netplan/
  
  bin:
    plugin: dump
    source: bin
    organize:
      "*": /bin/
      
